version: '3.7'
services:
    web:
        container_name: vc-server
        build:
            context: ./vc-server
            dockerfile: Dockerfile
        command: bash -c "make build_run"
        volumes:
            - './vc-server:/app/vc-server'
        ports:
            - 5000:5000

        networks:
            - internal
        stdin_open: true
    frontend:
        container_name: vc-frontend
        build:
          context: ./vc-frontend
          dockerfile: Dockerfile
        volumes:
          - './vc-frontend:/app'
        ports:
          - 8080:8080
        environment:
          - CHOKIDAR_USEPOLLING=true
        
volumes:
    server:
networks:
    internal:
      driver: bridge