version: '3.7'
services:
    server:
        container_name: ep-server
        build:
            context: ./server
            dockerfile: Dockerfile
        command: bash -c "go build && ./vc-server -b 0.0.0.0:8000 --timeout 120"
        volumes:
            - './vc-server:/app/server'
        ports:
            - 5000:5000
        depends_on: 
            - db
        networks:
            - internal
        stdin_open: true

    

  #frontend:
   # container_name: ep-client
    #build:
     # context: ./client
      #dockerfile: Dockerfile
    #volumes:
      #- './client:/app/client'
      #- '/app/node_modules'
    #ports:
      #- 3002:3000
    #environment:
      #- CHOKIDAR_USEPOLLING=true
    #stdin_open: true
####

volumes:
    server:
networks:
    internal:
      driver: bridge