// Mutation Types
export const UPDATE_BOARD_STATE = 'UPDATE_BOARD_STATE';
export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE';
export const SET_PLAYERS = 'SET_PLAYERS';
export const UPDATE_MEMBERS = 'UPDATE_MEMBERS';
export const SET_SRC_SELECTION = 'SET_SRC_SELECTION';
export const UNDO_SRC_SELECTION = 'UNDO_SRC_SELECTION';
export const PERFORM_MOVE = 'PERFORM_MOVE';
export const SET_SERVER_STATUS = 'SET_SERVER_STATUS';
export const SET_MOVE_PATTERNS = 'SET_MOVE_PATTERNS';
export const SET_RESULT = 'SET_RESULT';
export const SET_USER_INFO = 'SET_USER_INFO';
