package chess

import (
	"fmt"
	"unicode"
)

// VariantRules is the plug-in interface that each chess variant implements.
// All methods have sensible defaults via baseVariantRules; variants only override
// the behaviour they need.
type VariantRules interface {
	// ExtraMoves returns additional moves not generated by standard piece rules
	// (e.g. archer ranged attacks, teleportation moves).
	ExtraMoves(pos *Position, color Color) []Move

	// FilterMoves narrows the standard move list
	// (e.g. Antichess forces captures when they are available).
	FilterMoves(moves []Move, pos *Position) []Move

	// OnBeforeMove is called before a move is executed; return non-nil to reject it.
	OnBeforeMove(move Move, pos *Position) error

	// OnAfterMove is called right after a move is applied.
	// Implementations may update variant state (check counter, poison map, etc.)
	// and set result.IsGameOver / result.Result directly when needed.
	OnAfterMove(move Move, pos *Position, result *MoveResult)

	// CheckTermination returns an EngineResult if the game is over by variant rules,
	// or nil to fall through to standard checkmate / stalemate detection.
	CheckTermination(pos *Position) *EngineResult

	// VariantState returns the current variant-specific state for serialisation.
	VariantState() interface{}

	// LoadVariantState restores state from a deserialised value.
	LoadVariantState(s interface{}) error

	// Clone returns a deep copy of the rules including any mutable state.
	Clone() VariantRules
}

// variantFactory is set once by the chess/variants package via RegisterVariantFactory.
var variantFactory func(variantType string, customData map[string]interface{}) (VariantRules, error)

// RegisterVariantFactory wires in the variant implementation registry.
// It is called from chess/variants init().
func RegisterVariantFactory(f func(string, map[string]interface{}) (VariantRules, error)) {
	variantFactory = f
}

// newVariantRules resolves a variant type string to its VariantRules implementation.
// When the factory is registered (variants package imported), an unknown type returns an error.
// When no factory is registered, it falls back to baseVariantRules (used in tests that don't
// import the variants package).
func newVariantRules(variantType string, customData map[string]interface{}) (VariantRules, error) {
	if variantFactory != nil {
		return variantFactory(variantType, customData)
	}
	return &baseVariantRules{}, nil
}

// baseVariantRules is the default no-op VariantRules used when no factory is registered
// or when the variant type is unknown.
type baseVariantRules struct{}

func (r *baseVariantRules) ExtraMoves(_ *Position, _ Color) []Move             { return nil }
func (r *baseVariantRules) FilterMoves(moves []Move, _ *Position) []Move       { return moves }
func (r *baseVariantRules) OnBeforeMove(_ Move, _ *Position) error              { return nil }
func (r *baseVariantRules) OnAfterMove(_ Move, _ *Position, _ *MoveResult)     {}
func (r *baseVariantRules) CheckTermination(_ *Position) *EngineResult         { return nil }
func (r *baseVariantRules) VariantState() interface{}                           { return nil }
func (r *baseVariantRules) LoadVariantState(_ interface{}) error                { return nil }
func (r *baseVariantRules) Clone() VariantRules                                 { return &baseVariantRules{} }

// variant is the shared base embedded in all engine implementations.
type variant struct {
	*Position
	rules          VariantRules
	recentMove     RecentMoveInfo
	gameResult     *EngineResult
	isGameOverBool bool
}

func (v *variant) GetPieceAt(pos int) rune {
	for p, bitboard := range v.Pieces {
		if bitboard.HasBit(pos) {
			return p
		}
	}
	return 0
}

func (v *variant) CurrentTurn() Color {
	if v.Position.WhiteToMove {
		return White
	}
	return Black
}

func opponent(color Color) Color {
	if color == Black {
		return White
	}
	return Black
}

func (v *variant) SwitchTurn() {
	v.WhiteToMove = !v.WhiteToMove
}

// Variant is kept as an alias for Engine for backward compatibility.
type Variant = Engine

// NewEngine creates a new game engine from a GameConfig.
func NewEngine(gameConfig GameConfig) (Engine, error) {
	if gameConfig.FEN == "" {
		return nil, fmt.Errorf("GameConfig.FEN is required")
	}
	position, err := ParseFEN(gameConfig.FEN)
	if err != nil {
		return nil, err
	}

	// Apply custom piece rules from PieceProps.
	if gameConfig.PieceProps != nil {
		for pieceStr, props := range gameConfig.PieceProps {
			if len(pieceStr) != 1 {
				continue
			}
			pieceRune := rune(pieceStr[0])
			var patterns []MovePattern
			if len(props.SlideOffsets) > 0 {
				offsets := make([]*MoveOffset, len(props.SlideOffsets))
				for i, o := range props.SlideOffsets {
					offsets[i] = &MoveOffset{x: o.X, y: o.Y}
				}
				patterns = append(patterns, MovePattern{MoveType: Slide, MoveOffsets: offsets})
			}
			if len(props.JumpProps) > 0 {
				offsets := make([]*MoveOffset, len(props.JumpProps))
				for i, o := range props.JumpProps {
					offsets[i] = &MoveOffset{x: o.X, y: o.Y}
				}
				patterns = append(patterns, MovePattern{MoveType: Jump, MoveOffsets: offsets})
			}
			if len(patterns) > 0 {
				// Register for both colors — FEN uses 'd'/'D' but props are keyed lowercase.
				lower := unicode.ToLower(pieceRune)
				upper := unicode.ToUpper(pieceRune)
				position.CustomPieceRules[lower] = patterns
				position.CustomPieceRules[upper] = patterns
			}
		}
	}

	rules, err := newVariantRules(gameConfig.VariantType, gameConfig.CustomData)
	if err != nil {
		return nil, fmt.Errorf("variant %q: %w", gameConfig.VariantType, err)
	}
	v := variant{
		Position: position,
		rules:    rules,
	}
	return &StandardEngine{variant: v}, nil
}

// NewVariant is kept for backward compatibility; delegates to NewEngine.
func NewVariant(gameConfig GameConfig) (Engine, error) {
	return NewEngine(gameConfig)
}
