events {}

http {
    server {
        listen 80;
        server_name vc-server.com;

        location /ws/ {
            proxy_pass http://vc_ws:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
brew update
brew upgrade
brew doctor

        location /api/ {
            proxy_pass http://vc_core:5000;
            proxy_set_header Host $host;
        }
        location /health {
            proxy_pass http://vc_core:5000/health;
            proxy_set_header Host $host;
        }
    }
}
