name: Go CI

on:
  pull_request:
    branches: [ "main" ]
    paths: 
      - "vc-server/**"

jobs:
  build_server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: make build
        working-directory: vc-server
