name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: make build
        working-directory: vc-server
